# Generated by Django 5.0.6 on 2024-06-22 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessinflow",
            name="sold_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ops",
                to="business.businessexpenditure",
            ),
        ),
    ]
